name: KiCad nightly test

on:
  push:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp-n.yml'
  pull_request:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp-n.yml'

jobs:
  test:

    runs-on: ubuntu-latest
    container: setsoft/kicad_auto_test:nightly

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        KIAUS_USE_NIGHTLY: 5.99
      run: |
        python3-coverage erase
        pytest-3 --test_dir output
        python3-coverage report
        coveralls
    - name: Store results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: Test_Output
        path: output

