name: KiCad stable test

on:
  push:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'
  pull_request:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'

jobs:
  test:
    strategy:
      matrix:
        ki_release: [latest, nightly]

    runs-on: ubuntu-latest
    container: setsoft/kicad_auto_test:${{ matrix.ki_release }}

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
    - name: Test ${{ matrix.ki_release }}
      run: |
        make test_server_${{ matrix.ki_release }}
    - name: Store results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: Test_Output_${{ matrix.ki_release }}
        path: output
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        flag-name: run-${{ matrix.ki_release }}
        parallel: true
        path-to-lcov: .coverage

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel-finished: true
        path-to-lcov: .coverage

