name: Regression tests

on:
  push:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'
  pull_request:
    paths:
     - '**.py'
     - 'src/*_do'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'

jobs:
  test_normal:

    runs-on: ubuntu-latest
    container: setsoft/kicad_auto_test:latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
    - name: Test normal
      run: |
        make test_server_latest
    - name: Store results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: Test_Output_normal
        path: output
    - name: Upload Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_FLAG_NAME: latest
        COVERALLS_PARALLEL: true
      run: coveralls

  test_nightly:

    runs-on: ubuntu-latest
    container: setsoft/kicad_auto_test:nightly

    steps:
    - uses: actions/checkout@v2
    - name: Test nightly
      run: |
        make test_server_nightly
    - name: Store results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: Test_Output_nightly
        path: output
    - name: Upload Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_FLAG_NAME: nightly
        COVERALLS_PARALLEL: true
      run: coveralls

  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]="$GITHUB_RUN_ID"&payload[status]=done"

